// Generated by CoffeeScript 1.10.0
(function() {
  var persistence, should;

  should = require('should');

  persistence = require('../src/persistence');

  describe('persistence >', function() {
    before(function(done) {
      return persistence.open(function() {
        return done();
      });
    });
    it('do getTimeline', function(done) {
      return persistence.getTimeline(function(err, docs) {
        should.exist(docs);
        return done();
      });
    });
    it('find lastest score', function(done) {
      return persistence.findLastestScore(function(err, item) {
        console.log(item);
        return done();
      });
    });
    it('find period', function(done) {
      return persistence.findPeriodOfScore(function(err, item) {
        item.sort(function(a, b) {
          if (a.shortfile > b.shortfile) {
            return 1;
          } else {
            return -1;
          }
        });
        console.log(item[0]);
        console.log(item[item.length - 1]);
        return done();
      });
    });
    return it('find total commits count', function(done) {
      return persistence.findTotalCommits(function(err, docs) {
        return docs.toArray(function(err, doc) {
          var total;
          console.log(err);
          console.log(doc);
          total = 0;
          doc.forEach(function(item) {
            console.log(item._id + ":" + total + '+' + item.value);
            return total += item.value;
          });
          console.log(total);
          return done();
        });
      });
    });
  });

}).call(this);
